ElsetRec <- setRefClass("ElsetRec", fields = list(
    whichconst = "numeric",
    satid = "character",
    epochyr = "numeric",
    epochtynumrev = "numeric",
    error = "numeric",
    operationmode = "character",
    init = "character",
    method = "character",    
    a = "numeric",
    altp = "numeric",
    alta = "numeric",
    epochdays = "numeric",
    jdsatepoch = "numeric",
    jdsatepochF = "numeric",
    nddot = "numeric",
    ndot = "numeric",
    bstar = "numeric",
    rcse = "numeric",
    inclo = "numeric",
    nodeo = "numeric",
    ecco = "numeric",
    argpo = "numeric",
    mo = "numeric",
    no_kozai = "numeric",
    classification = "character",
    intldesg = "character",
    ephtype = "numeric",
    elnum = "numeric",
    revnum = "numeric",
    no_unkozai = "numeric",
    am = "numeric",
    em = "numeric",
    im = "numeric",
    Om = "numeric",
    om = "numeric",
    mm = "numeric",
    nm = "numeric",
    t = "numeric",
    tumin = "numeric",
    mu = "numeric",
    radiusearthkm = "numeric",
    xke = "numeric", 
    j2 = "numeric",
    j3 = "numeric",
    j4 = "numeric",
    j3oj2 = "numeric",
    dia_mm = "numeric", 
    period_sec = "numeric", 
    active = "character",
    not_orbital = "character",
    rcs_m2 = "numeric", 
    ep = "numeric",
    inclp = "numeric",
    nodep = "numeric",
    argpp = "numeric",
    mp = "numeric",
    isimp = "numeric",
    aycof = "numeric",
    con41 = "numeric",
    cc1 = "numeric",
    cc4 = "numeric",
    cc5 = "numeric",
    d2 = "numeric",
    d3 = "numeric",
    d4 = "numeric",
    delmo = "numeric",
    eta = "numeric",
    argpdot = "numeric",
    omgcof = "numeric",
    sinmao = "numeric",
    t2cof = "numeric",
    t3cof = "numeric",
    t4cof = "numeric",
    t5cof = "numeric",
    x1mth2 = "numeric",
    x7thm1 = "numeric",
    mdot = "numeric",
    nodedot = "numeric",
    xlcof = "numeric",
    xmcof = "numeric",
    nodecf = "numeric",
    irez = "numeric",
    d2201 = "numeric",
    d2211 = "numeric",
    d3210 = "numeric",
    d3222 = "numeric",
    d4410 = "numeric",
    d4422 = "numeric",
    d5220 = "numeric",
    d5232 = "numeric",
    d5421 = "numeric",
    d5433 = "numeric",
    dedt = "numeric",
    del1 = "numeric",
    del2 = "numeric",
    del3 = "numeric",
    didt = "numeric",
    dmdt = "numeric",
    dnodt = "numeric",
    domdt = "numeric",
    e3 = "numeric",
    ee2 = "numeric",
    peo = "numeric",
    pgho = "numeric",
    pho = "numeric",
    pinco = "numeric",
    plo = "numeric",
    se2 = "numeric",
    se3 = "numeric",
    sgh2 = "numeric",
    sgh3 = "numeric",
    sgh4 = "numeric",
    sh2 = "numeric",
    sh3 = "numeric",
    si2 = "numeric",
    si3 = "numeric",
    sl2 = "numeric",
    sl3 = "numeric",
    sl4 = "numeric",
    gsto = "numeric",
    xfact = "numeric",
    xgh2 = "numeric",
    xgh3 = "numeric",
    xgh4 = "numeric",
    xh2 = "numeric",
    xh3 = "numeric",
    xi2 = "numeric",
    xi3 = "numeric",
    xl2 = "numeric",
    xl3 = "numeric",
    xl4 = "numeric",
    xlamo = "numeric",
    zmol = "numeric",
    zmos = "numeric",
    atime = "numeric",
    xli = "numeric",
    xni = "numeric",
    snodm = "numeric",
    cnodm = "numeric",
    sinim = "numeric",
    cosim = "numeric",
    sinomm = "numeric",
    cosomm = "numeric",
    day = "numeric",
    emsq = "numeric",
    gam = "numeric",
    rtemsq = "numeric", 
    s1 = "numeric",
    s2 = "numeric",
    s3 = "numeric",
    s4 = "numeric",
    s5 = "numeric",
    s6 = "numeric",
    s7 = "numeric", 
    ss1 = "numeric",
    ss2 = "numeric",
    ss3 = "numeric",
    ss4 = "numeric",
    ss5 = "numeric",
    ss6 = "numeric",
    ss7 = "numeric",
    sz1 = "numeric",
    sz2 = "numeric",
    sz3 = "numeric",
    sz11 = "numeric",
    sz12 = "numeric",
    sz13 = "numeric",
    sz21 = "numeric",
    sz22 = "numeric",
    sz23 = "numeric",
    sz31 = "numeric",
    sz32 = "numeric",
    sz33 = "numeric",
    z1 = "numeric",
    z2 = "numeric",
    z3 = "numeric",
    z11 = "numeric",
    z12 = "numeric",
    z13 = "numeric",
    z21 = "numeric",
    z22 = "numeric",
    z23 = "numeric",
    z31 = "numeric",
    z32 = "numeric",
    z33 = "numeric",
    argpm = "numeric",
    inclm = "numeric",
    nodem = "numeric",
    dndt = "numeric",
    eccsq = "numeric",
    ainv = "numeric",
    ao = "numeric",
    con42 = "numeric",
    cosio = "numeric",
    cosio2 = "numeric",
    omeosq = "numeric",
    posq = "numeric",
    rp = "numeric",
    rteosq = "numeric",
    sinio = "numeric",
    rv = "ANY",
    vv = "ANY"
),
methods = list(
    initVals = function(){
    whichconst <<- 2 
    satnum <<- "0"
    epochyr <<- 0
    epochtynumrev <<- 0
    error <<- 0
    operationmode <<- "a"
    a <<- 0
    altp <<- 0
    alta <<- 0
    epochdays <<- 0
    jdsatepoch <<- 0
    jdsatepochF <<- 0
    nddot <<- 0
    ndot <<- 0
    bstar <<- 0
    rcse <<- 0
    inclo <<- 0
    nodeo <<- 0
    ecco <<- 0
    argpo <<- 0
    mo <<- 0
    no_kozai <<- 0
    classification <<- "U"
    ephtype <<- 0
    elnum <<- 0
    revnum <<- 0
    no_unkozai <<- 0
    am <<- 0
    em <<- 0
    im <<- 0
    Om <<- 0
    om <<- 0
    mm <<- 0
    nm <<- 0
    t <<- 0
    tumin <<- 0
    mu <<- 0
    radiusearthkm <<- 0
    xke <<- 0 
    j2 <<- 0
    j3 <<- 0
    j4 <<- 0
    j3oj2 <<- 0
    dia_mm <<- 0 
    period_sec <<- 0 
    rcs_m2 <<- 0 
    ep <<- 0
    inclp <<- 0
    nodep <<- 0
    argpp <<- 0
    mp <<- 0
    isimp <<- 0
    aycof <<- 0
    con41 <<- 0
    cc1 <<- 0
    cc4 <<- 0
    cc5 <<- 0
    d2 <<- 0
    d3 <<- 0
    d4 <<- 0
    delmo <<- 0
    eta <<- 0
    argpdot <<- 0
    omgcof <<- 0
    sinmao <<- 0
    t2cof <<- 0
    t3cof <<- 0
    t4cof <<- 0
    t5cof <<- 0
    x1mth2 <<- 0
    x7thm1 <<- 0
    mdot <<- 0
    nodedot <<- 0
    xlcof <<- 0
    xmcof <<- 0
    nodecf <<- 0
    irez <<- 0
    d2201 <<- 0
    d2211 <<- 0
    d3210 <<- 0
    d3222 <<- 0
    d4410 <<- 0
    d4422 <<- 0
    d5220 <<- 0
    d5232 <<- 0
    d5421 <<- 0
    d5433 <<- 0
    dedt <<- 0
    del1 <<- 0
    del2 <<- 0
    del3 <<- 0
    didt <<- 0
    dmdt <<- 0
    dnodt <<- 0
    domdt <<- 0
    e3 <<- 0
    ee2 <<- 0
    peo <<- 0
    pgho <<- 0
    pho <<- 0
    pinco <<- 0
    plo <<- 0
    se2 <<- 0
    se3 <<- 0
    sgh2 <<- 0
    sgh3 <<- 0
    sgh4 <<- 0
    sh2 <<- 0
    sh3 <<- 0
    si2 <<- 0
    si3 <<- 0
    sl2 <<- 0
    sl3 <<- 0
    sl4 <<- 0
    gsto <<- 0
    xfact <<- 0
    xgh2 <<- 0
    xgh3 <<- 0
    xgh4 <<- 0
    xh2 <<- 0
    xh3 <<- 0
    xi2 <<- 0
    xi3 <<- 0
    xl2 <<- 0
    xl3 <<- 0
    xl4 <<- 0
    xlamo <<- 0
    zmol <<- 0
    zmos <<- 0
    atime <<- 0
    xli <<- 0
    xni <<- 0
    snodm <<- 0
    cnodm <<- 0
    sinim <<- 0
    cosim <<- 0
    sinomm <<- 0
    cosomm <<- 0
    day <<- 0
    emsq <<- 0
    gam <<- 0
    rtemsq <<- 0 
    s1 <<- 0
    s2 <<- 0
    s3 <<- 0
    s4 <<- 0
    s5 <<- 0
    s6 <<- 0
    s7 <<- 0 
    ss1 <<- 0
    ss2 <<- 0
    ss3 <<- 0
    ss4 <<- 0
    ss5 <<- 0
    ss6 <<- 0
    ss7 <<- 0
    sz1 <<- 0
    sz2 <<- 0
    sz3 <<- 0
    sz11 <<- 0
    sz12 <<- 0
    sz13 <<- 0
    sz21 <<- 0
    sz22 <<- 0
    sz23 <<- 0
    sz31 <<- 0
    sz32 <<- 0
    sz33 <<- 0
    z1 <<- 0
    z2 <<- 0
    z3 <<- 0
    z11 <<- 0
    z12 <<- 0
    z13 <<- 0
    z21 <<- 0
    z22 <<- 0
    z23 <<- 0
    z31 <<- 0
    z32 <<- 0
    z33 <<- 0
    argpm <<- 0
    inclm <<- 0
    nodem <<- 0
    dndt <<- 0
    eccsq <<- 0
    ainv <<- 0
    ao <<- 0
    con42 <<- 0
    cosio <<- 0
    cosio2 <<- 0
    omeosq <<- 0
    posq <<- 0
    rp <<- 0
    rteosq <<- 0
    sinio <<- 0
  }    
)
)
